Fix ruin script to run in dev mode w/ virtualbox

diff --git a/tools/ruin b/tools/ruin
--- a/tools/ruin
+++ b/tools/ruin
@@ -1,27 +1,36 @@
 #!/usr/bin/env bash
 
+# The purpose of this script is to bootstrap Python so the install
+# script can be run.
+
+# Check to see if a dev flag was provided
+# Dev mode skips attempting to clone the project, and assumes
+# that it is located at $HOME/.hfor
 DEV=$1
-if [ -n "$DEV" ]; then
-	DEV="--dev"
+if [ -n "$DEV" ] && [ "$DEV" != "--dev" ]; then
+	echo "Invalid argument: $DEV"
+	exit 1
 fi
 
+# Determine the operating system and install Python the appropriate
+# way.
 OS=`uname -a`
-
-# OS specific things
 if [[ "$OS" == *"Darwin"* ]]; then
 	OS='macOS'
+	brew install python3
 elif [[ "$OS" == *"Ubuntu"* ]]; then
 	OS='Ubuntu'
-	sudo apt-get -y install git zsh vim curl wget python
-	sudo update-alternatives --set editor `which vim.basic`
+	sudo apt-get -y install python3
 else
 	echo "Unsupported OS: $OS"
 	exit 1
 fi
 
+# If not running in dev mode, clone the project to $HOME/.hfor
 if [ -z "$DEV" ]; then
 	git clone git@github.com:hurricanerix/hfor.git $HOME/.hfor
 fi
 
+# Change to the .hfor directory and run the installer
 cd $HOME/.hfor
-python tools/install.py $DEV $OS
+./tools/install.py $DEV $OS
